import test from 'node:test';import assert from 'node:assert/strict';
import {createHouse,mutate,visible,balance,identity,digest} from '../lib/model.js';
import {makeHandler} from '../api/household.js';
const setup=()=>createHouse({name:'Our home',names:['Sagar','Sushma','Nabin','Sujata'],seat:0});
const exp=(h,patch={})=>({merchant:'Groceries',cents:10001,category:'Groceries',payer:0,visibility:'shared',split:'half',date:'2026-09-13',sheet:h.sheets[0].id,notes:'',...patch});
test('equal splits conserve every cent, including odd totals',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});assert.deepEqual(balance(h.expenses),{net:5001,aPaid:10001,bPaid:0,amount:5001});mutate(h,2,{action:'expense',expense:exp(h,{payer:2})});assert.equal(balance(h.expenses).net,1);});
test('full allocations and own-couple expenses balance correctly',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h,{split:'b'})});assert.equal(balance(h.expenses).net,10001);mutate(h,2,{action:'expense',expense:exp(h,{payer:2,split:'a'})});assert.equal(balance(h.expenses).net,0);});
test('legacy couple-only records are visible to every member without adding debt',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});Object.assign(h.expenses[0],{visibility:'private',split:'half'});for(let seat=0;seat<4;seat++){const view=visible(h,seat);assert.equal(view.expenses.length,1);assert.equal(view.expenses[0].visibility,'shared');assert.equal(view.expenses[0].split,'a');assert.equal(view.keys,undefined);assert.equal(balance(view.expenses).amount,0);}assert.equal(balance(h.expenses).amount,0);assert.equal(h.expenses[0].visibility,'private','reading does not overwrite history');});
test('old clients cannot hide new entries',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h,{payer:2,visibility:'private'})});assert.equal(h.expenses[0].visibility,'shared');assert.equal(h.expenses[0].split,'b');assert.equal(balance(h.expenses).amount,0);for(let seat=0;seat<4;seat++)assert.equal(visible(h,seat).expenses.length,1);});
test('the payer cannot take ownership from the person who added the expense',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h,{payer:2})});const e=h.expenses[0];assert.throws(()=>mutate(h,2,{action:'expense',expense:{...e,creator:2,visibility:'private'}}),{status:403});assert.throws(()=>mutate(h,2,{action:'delete',id:e.id}),{status:403});mutate(h,0,{action:'expense',expense:{...e,cents:1234,creator:2}});assert.equal(h.expenses[0].creator,0);assert.equal(h.expenses[0].cents,1234);});
test('settlement locks all entries including legacy couple-only costs',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});mutate(h,0,{action:'expense',expense:exp(h,{visibility:'private'})});h.expenses[0].visibility='private';const before=balance(h.expenses).net;assert.equal(before,5001);mutate(h,0,{action:'settle',sheet:h.sheets[0].id});assert(h.expenses.every(e=>e.settlement));assert.equal(balance(h.expenses).net,0);for(const e of h.expenses){assert.throws(()=>mutate(h,0,{action:'delete',id:e.id}));assert.throws(()=>mutate(h,0,{action:'expense',expense:e}));}});
test('rejects invalid money and receipt payloads',()=>{for(const cents of [0,-1,1.1,NaN,1000000000]){const{h}=setup();assert.throws(()=>mutate(h,0,{action:'expense',expense:exp(h,{cents})}));}const{h}=setup();assert.throws(()=>mutate(h,0,{action:'expense',expense:exp(h,{receipt:'data:image/svg+xml,<script>'})}));});
test('only the author may edit or delete entries',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});for(const seat of [1,2,3]){assert.throws(()=>mutate(h,seat,{action:'delete',id:h.expenses[0].id}),{status:403});assert.throws(()=>mutate(h,seat,{action:'expense',expense:{...h.expenses[0],payer:seat,creator:seat}}),{status:403});}});
test('archiving requires shared settlement and prevents new entries',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});assert.throws(()=>mutate(h,0,{action:'archive',id:h.sheets[0].id}));mutate(h,0,{action:'settle',sheet:h.sheets[0].id});mutate(h,0,{action:'archive',id:h.sheets[0].id});assert.throws(()=>mutate(h,0,{action:'expense',expense:exp(h)}));});
test('private access key is stored as a hash and checked',()=>{const{h,key}=setup();assert.equal(identity(h,key),0);assert.equal(h.keys[0],digest(key));assert.notEqual(h.keys[0],key);assert.throws(()=>identity(h,'wrong'));});
function fakeDb(){const m=new Map();return async(cmd,...a)=>{if(cmd==='GET')return m.get(a[0])??null;if(cmd==='SET'){if(a[2]==='NX'&&m.has(a[0]))return null;m.set(a[0],a[1]);return'OK';}if(cmd==='INCR'){const v=(m.get(a[0])||0)+1;m.set(a[0],v);return v;}if(cmd==='EXPIRE')return 1;if(cmd==='EVAL'){const[,key,old,next]=a.slice(1);if(m.get(key)!==old)return 0;m.set(key,next);return 1;}};}
async function request(fn,body,key='',headers={}){let code;let result;const res={setHeader(){},status(c){code=c;return this;},json(j){result=j;return this;}};await fn({method:'POST',headers:{host:'example.com',authorization:'Bearer '+key,...headers},body},res);return{code,...result};}
test('API create, join, read, edit and stale revision rejection',async()=>{const fn=makeHandler(fakeDb());const owner=await request(fn,{action:'create',name:'Home',names:['A','B','C','D'],seat:0});assert.equal(owner.code,200);const house=owner.data.id;const joined=await request(fn,{action:'join',house,invite:owner.data.invite,seat:2});assert.equal(joined.code,200);const now=await request(fn,{action:'read',house},owner.key);assert.equal(now.code,200);const saved=await request(fn,{action:'expense',house,rev:now.data.rev,expense:exp(now.data,{visibility:'private'})},owner.key);assert.equal(saved.code,200);const outsider=await request(fn,{action:'read',house},joined.key);assert.equal(outsider.data.expenses.length,1);const stale=await request(fn,{action:'settings',house,rev:now.data.rev,name:'Changed',names:['A','B','C','D']},owner.key);assert.equal(stale.code,409);const invalid=await request(fn,{action:'read',house},'x'.repeat(64));assert.equal(invalid.code,401);});
test('API rejects cross-origin requests and duplicate seat claims',async()=>{const fn=makeHandler(fakeDb());assert.equal((await request(fn,{action:'create'},'',{origin:'https://evil.example'})).code,403);const owner=await request(fn,{action:'create',name:'Home',names:['A','B','C','D'],seat:0});assert.equal((await request(fn,{action:'join',house:owner.data.id,invite:owner.data.invite,seat:0})).code,409);});

test('API author permissions reject payer edits, deletes, creator spoofing and bulk deletion',async()=>{
 const fn=makeHandler(fakeDb());const owner=await request(fn,{action:'create',name:'Home',names:['A','B','C','D'],seat:0});const house=owner.data.id;
 const payer=await request(fn,{action:'join',house,invite:owner.data.invite,seat:2});
 const saved=await request(fn,{action:'expense',house,rev:payer.data.rev,expense:exp(payer.data,{payer:2,creator:2})},owner.key);
 assert.equal(saved.code,200);const e=saved.data.expenses[0];assert.equal(e.creator,0);
 for(const action of [{action:'expense',expense:{...e,creator:2,cents:1}},{action:'delete',id:e.id},{action:'sheet-delete',id:e.sheet}]){
  const denied=await request(fn,{...action,house,seat:0,rev:saved.data.rev},payer.key);assert.equal(denied.code,403);
 }
 const read=await request(fn,{action:'read',house},payer.key);assert.equal(read.data.expenses[0].cents,10001);assert.equal(read.data.rev,saved.data.rev);
 const edited=await request(fn,{action:'expense',house,rev:read.data.rev,expense:{...e,cents:2500}},owner.key);assert.equal(edited.code,200);
 const deleted=await request(fn,{action:'delete',house,rev:edited.data.rev,id:e.id},owner.key);assert.equal(deleted.code,200);assert.equal(deleted.data.expenses.length,0);
});
test('creator-only permissions hold for every author and payer combination',()=>{
 for(let author=0;author<4;author++)for(let payer=0;payer<4;payer++){
  const{h}=setup();mutate(h,author,{action:'expense',expense:exp(h,{payer,creator:(author+1)%4})});const e=h.expenses[0];assert.equal(e.creator,author);
  for(let seat=0;seat<4;seat++)if(seat!==author){const before=JSON.stringify(h);for(const action of [{action:'expense',expense:{...e,payer:seat,creator:seat}},{action:'delete',id:e.id},{action:'sheet-delete',id:e.sheet}])assert.throws(()=>mutate(h,seat,action),{status:403});assert.equal(JSON.stringify(h),before);}
  mutate(h,author,{action:'expense',expense:{...e,payer:(payer+1)%4,cents:7,creator:(author+1)%4}});assert.equal(h.expenses[0].creator,author);mutate(h,author,{action:'delete',id:e.id});assert.equal(h.expenses.length,0);
 }
});
test('missing legacy author remains read-only, never inferred from payer',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});delete h.expenses[0].creator;const e=h.expenses[0];for(let seat=0;seat<4;seat++){assert.equal(visible(h,seat).expenses.length,1);assert.throws(()=>mutate(h,seat,{action:'expense',expense:{...e,creator:seat}}),{status:403});assert.throws(()=>mutate(h,seat,{action:'delete',id:e.id}),{status:403});}});

test('previously archived sheets with couple-only costs can still be reopened',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});h.expenses[0].visibility='private';h.sheets[0].archived=true;mutate(h,0,{action:'archive',id:h.sheets[0].id});assert.equal(h.sheets[0].archived,false);mutate(h,0,{action:'expense',expense:{...visible(h,0).expenses[0],notes:'Updated'}});assert.equal(h.expenses[0].notes,'Updated');});
